version: '3'
volumes:
  dados:
services:
  #backend:
  #  image: python:3.6
  #  volumes:
  #    - ./backend:/backend
  #  working_dir: /backend
  #  command: bash ./app.sh
  #  ports:
  #    - 8080:8080
  db: 
    image: postgres:9.6
    volumes:
      - dados:/var/lib/postgres/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432
  #frontend:
  #  image: nginx:1.13
  #  volumes:
  #    - ./frontend:/usr/share/nginx/html
  #  ports:
  #    - 80:80